../../verilog/constants.sv
../../verilog/functions.sv
../../verilog/wires.sv
../../verilog/alu.sv
../../verilog/agu.sv
../../verilog/bcu.sv
../../verilog/fetch_stage.sv
../../verilog/decode_stage.sv
../../verilog/execute_stage.sv
../../verilog/cpu.sv
../../verilog/tb/test_cpu.sv
