../../verilog/constants.sv
../../verilog/functions.sv
../../verilog/wires.sv
../../verilog/alu.sv
../../verilog/agu.sv
../../verilog/bcu.sv
../../verilog/lsu.sv
../../verilog/csr_alu.sv
../../verilog/decoder.sv
../../verilog/register.sv
../../verilog/csr.sv
../../verilog/forwarding.sv
../../verilog/fetch_stage.sv
../../verilog/decode_stage.sv
../../verilog/execute_stage.sv
../../verilog/arbiter.sv
../../verilog/cpu.sv
../../verilog/tb/configure.sv
../../verilog/tb/memory.sv
../../verilog/tb/top_cpu.sv
